name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: Repository environment
        type: environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: extractions/setup-just@v3
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUPER_GITHUB_TOKEN }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Configure environment
        run: >
          echo """${{ secrets.DOTENV_FILE }}""" >> .env

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Turn off bricks
        run: npm run brickyard:disable

      - name: Build ui
        run: npm i && npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "seewe"
          exclude: |
            e2e
            src
            .github
            .vscode
            .git
            .gitignore
          entrypoint: api/mod.ts
