name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: Repository environment
        type: environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: extractions/setup-just@v3
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - uses: kindkitchen/genv@v1.0.0
        with:
          secrets_obj: ${{ toJson(secrets) }}
          content_from_secrets_include_pattern: "DOTENV_CONTENT"

      - run: cat .env
      - uses: actions/setup-node@v4
      - run: just brickyard-disable
      - run: just install
      - run: just build

      - uses: denoland/deployctl@v1
        with:
          project: "seewe"
          include: |
            dist
            api
          entrypoint: api/mod.ts
